config/routes.rb
Rails.application.routes.draw do
  resources :trips do
    resources :destinations, controller: 'trip_destinations'
    resources :users
  end
  resources :destinations
  resources :users do
    resources :trips
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trip.rb
class Trip < ApplicationRecord
  include Sluggable
  
  has_many :trip_destinations
  has_many :destinations, through: :trip_destinations

  has_many :trip_users
  has_many :users, through: :trip_users
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @destination = Destination.new
  end

  # GET /trips/new
  def new
    @trip = Trip.new
    @user = User.find_by(slug: params[:user_id])
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @user = User.find_by(slug: params[:user_id])
    @trip = @user.trips.create(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find_by(slug: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:name)
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for([user, trip]) do |f| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <h4 class="text-uppercase">Name</h4>
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trips</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= link_to trip.name, trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip, user: @user %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-sm-3">
    Trip Name: <%= @trip.name %>
  </div>
</div>

<div class="row">
  <h4>Trip Users</h4>
  <% @trip.users.each do |user| %>
    <div class="row">
      <div class="col-sm-3">
        Name: <%= link_to user.name, user %>
      </div>
    </div>
  <% end %>
</div>

<div class="row">
  <h4>Destinations</h4>
  <% @trip.destinations.each do |destination| %>
    <div class="row">
      <div class="col-sm-3">
        Name: <%= destination.name %>
      </div>
    </div>
  <% end %>
</div>

<%= form_for [@trip, @destination], url: trip_destinations_path(@trip), method: :post do |f| %>
  <td><%= f.collection_select :name, Destination.all, :slug, :name %></td>
  <td><%= f.submit 'Add Destination', class: 'btn btn-sm btn-primary' %></td>
<% end %>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>